name: DEV
values:
  - key: farm-endpoint
    value: ''
  - key: natural-person-endpoint
    value: ''
  - key: legal-person-endpoint
    value: ''
  - key: residence-certificates-endpoint
    value: ''
  - key: ui-config/forms/submit-endpoint
    value: ''
color: 0
