name: NC_TEST
values:
  - key: farm-endpoint
    value: ''
  - key: natural-person-endpoint
    value: ''
  - key: legal-person-endpoint
    value: ''
  - key: residence-certificates-endpoint
    value: ''
color: 240
