name: NC_TEST
values:
  - key: farm-endpoint
    value: ''
  - key: natural-person-endpoint
    value: ''
  - key: legal-person-endpoint
    value: ''
  - key: residence-certificates-endpoint
    value: ''
  - key: ui-config/forms/submit-endpoint
    value: ''
  - key: addressId
    value: ''
  - key: addressObjectTypeCode
    value: ''
  - key: residenceAddress
    value: ''
color: 240
